const makermenu = (prefix) => { 
	return `       
	
*🔧 MAKER MENU*
⎆ ${prefix}sticker
⎆ ${prefix}ttp
⎆ ${prefix}attp
⎆ ${prefix}nulis
⎆ ${prefix}nulis2
⎆ ${prefix}shadow
⎆ ${prefix}cup
⎆ ${prefix}cup1
⎆ ${prefix}romance
⎆ ${prefix}smoke
⎆ ${prefix}burnpaper
⎆ ${prefix}lovemessage
⎆ ${prefix}undergrass
⎆ ${prefix}love
⎆ ${prefix}coffe
⎆ ${prefix}woodheart
⎆ ${prefix}flowerheart
⎆ ${prefix}woodenboard
⎆ ${prefix}summer3d
⎆ ${prefix}wolfmetal
⎆ ${prefix}nature3d
⎆ ${prefix}underwater
⎆ ${prefix}golderrose
⎆ ${prefix}summernature
⎆ ${prefix}letterleaves
⎆ ${prefix}glowingneon
⎆ ${prefix}fallleaves
⎆ ${prefix}flamming
⎆ ${prefix}harrypotter
⎆ ${prefix}carvedwood
⎆ ${prefix}wetglass
⎆ ${prefix}multicolor3d
⎆ ${prefix}watercolor
⎆ ${prefix}luxurygold
⎆ ${prefix}galaxywallpaper
⎆ ${prefix}lighttext
⎆ ${prefix}beautifulflower
⎆ ${prefix}puppycute
⎆ ${prefix}royaltext
⎆ ${prefix}heartshaped
⎆ ${prefix}birthdaycake
⎆ ${prefix}galaxystyle
⎆ ${prefix}hologram3d
⎆ ${prefix}glossychrome
⎆ ${prefix}greenbush
⎆ ${prefix}metallogo
⎆ ${prefix}noeltext
⎆ ${prefix}glittergold
⎆ ${prefix}textcake
⎆ ${prefix}starsnight
⎆ ${prefix}wooden3d
⎆ ${prefix}textbyname
⎆ ${prefix}writegalacy
⎆ ${prefix}galaxybat
⎆ ${prefix}snow3d
⎆ ${prefix}birthdayday
⎆ ${prefix}goldplaybutton
⎆ ${prefix}silverplaybutton
⎆ ${prefix}freefire
⎆ ${prefix}tahta
⎆ ${prefix}darkneon
⎆ ${prefix}candlemug
⎆ ${prefix}lovemsg
⎆ ${prefix}mugflower
⎆ ${prefix}narutobanner [MAINTENANCE]
⎆ ${prefix}paperonglass
⎆ ${prefix}romancetext
⎆ ${prefix}shadowtext
⎆ ${prefix}coffeecup
⎆ ${prefix}coffeecup2
⎆ ${prefix}glowingneon
⎆ ${prefix}underwater
⎆ ${prefix}hpotter
⎆ ${prefix}woodblock
⎆ ${prefix}gplaybutton
⎆ ${prefix}splaybutton
⎆ ${prefix}barcode
⎆ ${prefix}qrencode
⎆ ${prefix}ttp
⎆ ${prefix}ttp2
⎆ ${prefix}ttp3
⎆ ${prefix}ttp4
⎆ ${prefix}attp
⎆ ${prefix}jokerlogo
⎆ ${prefix}calendermaker
⎆ ${prefix}pornhub 
⎆ ${prefix}ktpfake
⎆ ${prefix}googletext
⎆ ${prefix}glitchtext
⎆ ${prefix}crosslogo
⎆ ${prefix}naruto [MAINTENANCE]
⎆ ${prefix}flowertext
⎆ ${prefix}silktext
⎆ ${prefix}flametext
⎆ ${prefix}glowtext
⎆ ${prefix}skytext
⎆ ${prefix}cslogo
⎆ ${prefix}lithgtext
⎆ ${prefix}crismes
⎆ ${prefix}bneon
⎆ ${prefix}matrix
⎆ ${prefix}breakwall
⎆ ${prefix}dropwater
⎆ ${prefix}leavest
⎆ ${prefix}logobp
⎆ ${prefix}fftourserti
⎆ ${prefix}fftourserti2
⎆ ${prefix}fftourserti3
⎆ ${prefix}fftourserti4
⎆ ${prefix}fftourserti5
⎆ ${prefix}pubgtourserti
⎆ ${prefix}pubgtourserti2
⎆ ${prefix}pubgtourserti3
⎆ ${prefix}pubgtourserti4
⎆ ${prefix}pubgtourserti5
⎆ ${prefix}mltourserti
⎆ ${prefix}mltourserti2
⎆ ${prefix}mltourserti3
⎆ ${prefix}mltourserti4
⎆ ${prefix}mltourserti5
⎆ ${prefix}tweetfake
⎆ ${prefix}babu
⎆ ${prefix}bucinserti
⎆ ${prefix}bocilepep
⎆ ${prefix}gayserti
⎆ ${prefix}pacar
⎆ ${prefix}sadboy
⎆ ${prefix}surga
⎆ ${prefix}pintar
⎆ ${prefix}badboy
⎆ ${prefix}badgirl
⎆ ${prefix}goodboy
⎆ ${prefix}goodgirl
⎆ ${prefix}editorberkelas
⎆ ${prefix}phcomment nama/comen
⎆ ${prefix}wallgravity teks1/teks2
⎆ ${prefix}marvelstudio teks1/teks2
⎆ ${prefix}space teks1/teks2 `

}

exports.makermenu = makermenu
