const nsfwmenu=(prefix)=>{
	return`
	
	
*⧉NSFWMENU*
⎆${prefix}randomhentai
⎆${prefix}randomsfw
⎆${prefix}randomnsfw
⎆${prefix}sfw
⎆${prefix}nsfw
⎆${prefix}nsfwneko
⎆${prefix}randombokep
⎆${prefix}pussy
⎆${prefix}nekonime
⎆${prefix}baka
⎆${prefix}blowjob
⎆${prefix}lewd
⎆${prefix}hentai
⎆${prefix}waifu
⎆${prefix}eroyuri
⎆${prefix}hug
⎆${prefix}hug2
⎆${prefix}chiisaihentai
⎆${prefix}trap
⎆${prefix}blowjob
⎆${prefix}yaoi
⎆${prefix}ecchi
⎆${prefix}hentai
⎆${prefix}ahegao
⎆${prefix}hololewd
⎆${prefix}sideoppai
⎆${prefix}animefeets
⎆${prefix}animebooty
⎆${prefix}animethighss
⎆${prefix}hentaiparadise
⎆${prefix}animearmpits
⎆${prefix}hentaifemdom
⎆${prefix}lewdanimegirls
⎆${prefix}biganimetiddies
⎆${prefix}animebellybutton
⎆${prefix}hentai4everyone
⎆${prefix}ero
⎆${prefix}cum
⎆${prefix}feet
⎆${prefix}yuri
⎆${prefix}trap
⎆${prefix}lewd
⎆${prefix}feed
⎆${prefix}eron
⎆${prefix}solo
⎆${prefix}gasm
⎆${prefix}poke
⎆${prefix}anal
⎆${prefix}holo
⎆${prefix}tits
⎆${prefix}kuni
⎆${prefix}kiss
⎆${prefix}erok
⎆${prefix}smug
⎆${prefix}baka
⎆${prefix}solog
⎆${prefix}feetg
⎆${prefix}lewdk
⎆${prefix}waifu
⎆${prefix}pussy
⎆${prefix}femdom
⎆${prefix}cuddle
⎆${prefix}hentai
⎆${prefix}eroyuri
⎆${prefix}cum_jpg
⎆${prefix}blowjob
⎆${prefix}erofeet
⎆${prefix}holoero
⎆${prefix}classic
⎆${prefix}erokemo
⎆${prefix}fox_girl
⎆${prefix}futanari
⎆${prefix}lewdkemo
⎆${prefix}wallpaper
⎆${prefix}pussy_jpg
⎆${prefix}kemonomimi
⎆${prefix}nsfw_avatar
⎆${prefix}nhentai
⎆${prefix}nhentaisearch
⎆${prefix}nhentaipdf
⎆${prefix}nekopoi
⎆${prefix}nekopoisearch
⎆${prefix}xhamstersearch
⎆${prefix}xhamster
⎆${prefix}xnxxsearch
⎆${prefix}xnxx`
}

exports.nsfwmenu=nsfwmenu
