const tourff = (prefix) => {
        return `
*5K 4 MATCH KAPAN LAGI?!!*
*TESTI BANYAK. RAGU? TANYA TESTI*

*FAST TOURNAMENT BY JANCOKSHOP*

TOTAL POOLPRIZE : Rp35.000,00

*JUARA 1 🏆: RP16.000,00 + SERTIFICATE*
*JUARA 2 🏆: RP12.000,00 + SERTIFICATE*
*JUARA 3 🏆: RP7.000,00 + SERTIFICATE*

*FEE REGIST : Rp5.000TEAM   GO-PAY*
*PULSA : 10K*
*QRIS : 7K*

*📍 MODE SQUAD*
*📍 12 SLOT*
*📍 SISTEM POINT*
*📍 4 MATCH*
*📍 B-P-K-P*
*📍 NO EMULATOR + NICK OREN*

*SESI 1 : 14:00 WIB (CLOSE)*
*SESI 2 : 15:00 WIB (CLOSE)*
*SESI 3 : 20:00 WIB (CLOSE)*
*SESI 4 : 22.00 WIB (CLOSE)*
*SESI 5 : 23.00 WIB (CLOSE)*

*MAIN EVENT : FULLSLOT*

NOTE : JANGAN TAKUT GK FULL INSYALLAH PSTI FULL GAN 🙏🏻
_Contact Person_

Q&A:
Q : BANG KOK OPEN BANYAK SESI? NGERIP YAH? 
A : ADMINNYA BANYAK YAH OPEN BANYAK SESI. KALO RAGU TANYA TESTI

ADMIN  :
Wa.me/62895325677273 (DANZ) 

Notes: Tolong Daftar sesuai admin sesi 🙏🏻
Jika ada masalah Dengan FT Chat Admin 1.

_Penanggung jawab_

@danz.nih._
@ff.firebold
@jancokshop_

🔰LINK GRUP INFO FT/FM BY DANZ 2 ( BANTU FULLKAN) 
https://chat.whatsapp.com/EzXrwYshjxJLCODT3Ieb6p 
`
}
exports.tourff = tourff
